### ISSUE TITLE
DoProduction out of range  at Supremacy.Buildings.BuildingDesign.TrySpawn..

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#430] opened 2019-11-09 13:50 UTC
06:41:55.994 [41] ERROR Production Supremacy.Game.GameEngine+<>c__DisplayClass40_0.<DoProduction>b__0() - DoProduction failed for Terran Empire
System.ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Supremacy.Collections.IndexedCollection`1.InsertItem(Int32 listIndex, T item, Boolean upgradeableLockAlreadyHeld) in C:\Users\kenne\Documents\89_BOTF2_20191011\SupremacyCore\Collections\IndexedCollection.cs:line 359
   at Supremacy.Collections.IndexedCollection`1.Add(T item) in C:\Users\kenne\Documents\89_BOTF2_20191011\SupremacyCore\Collections\IndexedCollection.cs:line 340
   at Supremacy.Buildings.BuildingDesign.TrySpawn(MapLocation location, Civilization owner, TechObject& spawnedInstance) in C:\Users\kenne\Documents\89_BOTF2_20191011\SupremacyCore\Buildings\BuildingDesign.cs:line 260
   at Supremacy.Economy.BuildProject.Finish() in C:\Users\kenne\Documents\89_BOTF2_20191011\SupremacyCore\Economy\BuildProject.cs:line 424
   at Supremacy.Game.GameEngine.<>c__DisplayClass40_0.<DoProduction>b__0(Civilization civ) in C:\Users\kenne\Documents\89_BOTF2_20191011\SupremacyCore\Game\GameEngine.cs:line 1500
06:41:56.509 [35] DEBUG General Supremacy.Universe.UniverseManager.Find() - Find Object Type StarSystem
06:41:56.615 [4] DEBUG General Supremacy.Universe.UniverseManager.Find() - Find Object Type Fleet
06:41:56.618 [4] INFO  General Supremacy.Game.GameContext.OnTurnNumberChanged() - ------------------------------ TURN 8 ------------------------------
06:41:56.721 [4] INFO  General Supremacy.WCF.SupremacyService+<ProcessTurn>d__47.MoveNext() - Turn processing time: 00:00:25.5835072
06:41:56.723 [35] INFO  General Supremacy.Game.SavedGameManager.AutoSave() - saving C:\Users\kenne\AppData\Local\Star Trek Supremacy\Saved Games\.autosav
06:41:56.985 [1] INFO  General Supremacy.Game.GameContext.OnTurnNumberChanged() - ------------------------------ TURN 8 ------------------------------

**Comment by ExultantMonkey** [comment] 2019-11-19 21:18
Duplicate of #324 I suspect

**Comment by bote-reginald** [comment] 2022-06-04 15:21
"too old" - maybe not relevant anymore

**Closed by bote-reginald** 2022-06-04 15:21 UTC
Labels: bug
